"""Ex-ante (implied) skewness of the bet on the favourite, from de-vigged
probabilities — the study's PRIMARY object.

For a unit bet on the favourite at decimal odd o and true prob. p:
    return = (o-1) with prob p ;  -1 with prob (1-p)
It is a two-point distribution (rescaled Bernoulli), with closed-form central
moments:
    mean   mu = p*o - 1
    var    s2 = p(1-p) o²
    3rd    m3 = p(1-p)(1-2p) o³
The PER-GAME skewness depends only on p:   (1-2p)/√(p(1-p))  → crosses 0 at p=0.5.
The POOLED skewness (league/window) is that of the mixture of these games,
decomposed via the law of total cumulants — separating the mechanical term
(intra-game asymmetry, the FLB) from the between-game dispersion. This is what
defuses the tautology criticism: market skewness is, to 1st order, the algebraic
image of the distribution of p.
"""
from math import comb
import numpy as np, pandas as pd
from . import devig


def _fav(df):
    """de-vigged odd and prob of the favourite (= argmax p = argmin odd)."""
    P = df[["p_H", "p_D", "p_A"]].to_numpy(float)
    O = df[["OddHome", "OddDraw", "OddAway"]].to_numpy(float)
    j = P.argmax(axis=1)
    i = np.arange(len(P))
    return P[i, j], O[i, j]


def per_match_moments(p, o):
    """Central moments (mean, variance, 3rd) of the two-point bet."""
    mu = p * o - 1.0
    s2 = p * (1 - p) * o ** 2
    m3 = p * (1 - p) * (1 - 2 * p) * o ** 3
    return mu, s2, m3


def per_match_skew(p):
    """Ex-ante skewness of a single game — only a function of p."""
    p = np.asarray(p, float)
    return (1 - 2 * p) / np.sqrt(p * (1 - p))


def per_match_central_moments(p, o, max_order=6):
    """PER-GAME central moments of the two-point bet, orders 0..max_order.

    Closed form for all orders (the bet is a rescaled Bernoulli):
        m_k = o^k · p(1-p) · [ (1-p)^(k-1) + (-1)^k · p^(k-1) ],   m_0=1, m_1=0.
    Recovers m_2 = o²p(1-p) and m_3 = o³p(1-p)(1-2p) from `per_match_moments`.
    Returns a list `m` with m[k] = per-game array (m[0]≡1, m[1]≡0).
    """
    p = np.asarray(p, float); o = np.asarray(o, float)
    pp = p * (1 - p)
    m = [np.ones_like(p), np.zeros_like(p)]
    for k in range(2, max_order + 1):
        m.append(o ** k * pp * ((1 - p) ** (k - 1) + (-1) ** k * p ** (k - 1)))
    return m


def pooled_moments(p, o, max_order=6):
    """Moments of the MIXTURE (league/window) + mechanical fraction per order.

    Generalises `pooled_skew` to the entire shape of the implied distribution. The
    central moments of the mixture come from the law of total moments (equal
    weight, deviation from the game mean d_i = mu_i − M1):
        M_k = E_i[ Σ_{j=0..k} C(k,j) · m_{j,i} · d_i^(k-j) ]   (m_0=1, m_1=0)
      → M2 = E[m2]+E[d²];  M3 = E[m3]+3E[m2·d]+E[d³];
        M4 = E[m4]+4E[m3·d]+6E[m2·d²]+E[d⁴]; likewise 5/6.
    The `within` fraction (= E[m_k]/M_k) measures how much of each moment is
    MECHANICAL (intra-game asymmetry/shape, the FLB) vs generated by the
    between-game dispersion. Returns var/skew/exkurt + standardised 5/6, M_k,
    within_frac per order, and the 3-way decomposition of M3
    (within3/cov3/between3) used by `pooled_skew`.
    """
    p = np.asarray(p, float); o = np.asarray(o, float)
    mu = p * o - 1.0
    m = per_match_central_moments(p, o, max_order)
    M1 = mu.mean()
    d = mu - M1
    Mk, within = {}, {}
    res = {"mean": float(M1)}
    for k in range(2, max_order + 1):
        s = np.zeros_like(p)
        for j in range(0, k + 1):
            if j == 1:
                continue                       # m_1 = 0
            s = s + comb(k, j) * m[j] * d ** (k - j)
        Mk[k] = float(s.mean())
        within[k] = float(m[k].mean())
        res[f"M{k}"] = Mk[k]
        res[f"within_frac_m{k}"] = within[k] / Mk[k] if Mk[k] != 0 else float("nan")
    M2 = Mk[2]
    res["var"] = M2
    if max_order >= 3:
        res["skew"] = Mk[3] / M2 ** 1.5
        # 3-way decomposition of M3 (compatibility with pooled_skew)
        res["within3"]  = within[3]
        res["cov3"]     = float((comb(3, 2) * m[2] * d).mean())   # 3·E[m2·d]
        res["between3"] = float((d ** 3).mean())
    if max_order >= 4:
        res["exkurt"] = Mk[4] / M2 ** 2 - 3.0
    if max_order >= 5:
        res["std5"] = Mk[5] / M2 ** 2.5
    if max_order >= 6:
        res["std6"] = Mk[6] / M2 ** 3
    return res


def pooled_skew(p, o):
    """Skewness of the mixture + decomposition (law of total moments).

        M3 = E[m3_i]                  (mechanical: intra-game asymmetry / FLB)
           + 3·E[s2_i·(mu_i-mu)]      (variance×mean covariance)
           + E[(mu_i-mu)³]            (between-game dispersion)
        V  = E[s2_i] + Var(mu_i),   skew = M3 / V^1.5.

    3rd-order case of `pooled_moments`; keeps the explicit forms
    of `per_match_moments` for output bit-identical to the frozen baseline.
    """
    p = np.asarray(p, float); o = np.asarray(o, float)
    mu, s2, m3 = per_match_moments(p, o)
    d = mu - mu.mean()
    within  = m3.mean()
    cov     = 3.0 * (s2 * d).mean()
    between = (d ** 3).mean()
    M3 = within + cov + between
    V = s2.mean() + d.var()
    skew = M3 / V ** 1.5
    return {"skew": float(skew), "M3": float(M3), "V": float(V),
            "within": float(within), "cov": float(cov), "between": float(between),
            "within_frac": float(within / M3), "cov_frac": float(cov / M3),
            "between_frac": float(between / M3)}


def market_skew(df, odd_cols, method=None):
    """De-vigs any 1X2 market (e.g.: average vs maximum odds) and returns
    (p_fav, o_fav, pooled decomposition). Used in the margin orthogonality test:
    does the skewness change across bookmakers/margins?"""
    dd = devig.devig_frame(df, method=method, cols=odd_cols)
    P = dd[["p_H", "p_D", "p_A"]].to_numpy(float)
    O = df[list(odd_cols)].to_numpy(float)
    j = P.argmax(axis=1); i = np.arange(len(P))
    p, o = P[i, j], O[i, j]
    return p, o, pooled_skew(p, o)


def add_exante(df, method=None):
    """De-vigs, identifies the favourite and adds p_fav_dv, o_fav, skew_exante_match."""
    out = devig.devig_frame(df, method=method)
    p, o = _fav(out)
    out["p_fav_dv"] = p
    out["o_fav"] = o
    out["skew_exante_match"] = per_match_skew(p)
    return out


def fav_dog_draw(df):
    """(de-vigged p, market o) of the THREE betting objects, per game:
    favourite (argmax p / minimum odd), draw (outcome D), longshot (argmin p /
    maximum odd). Requires a df already de-vigged (p_H/p_D/p_A) with OddHome/Draw/Away.
    The favourite coincides with (p_fav_dv, o_fav) from `add_exante`."""
    P = df[["p_H", "p_D", "p_A"]].to_numpy(float)
    O = df[["OddHome", "OddDraw", "OddAway"]].to_numpy(float)
    i = np.arange(len(P))
    jf, jd = P.argmax(axis=1), P.argmin(axis=1)
    return {"fav": (P[i, jf], O[i, jf]),
            "draw": (P[:, 1], O[:, 1]),
            "dog": (P[i, jd], O[i, jd])}


def bettype_by(df, col="Division", min_n=2000):
    """POOLED ex-ante skewness of the three betting objects (favourite/draw/
    longshot) per group. One row per league with skew_fav/skew_draw/skew_dog and the
    competitiveness (mean of p_fav) — the basis of the bet-type radar."""
    rows = []
    for key, g in df.groupby(col, observed=True):
        if len(g) < min_n:
            continue
        sel = fav_dog_draw(g)
        row = {col: key, "n": int(len(g)),
               "p_fav_mean": float(sel["fav"][0].mean())}
        for name, (p, o) in sel.items():
            row[f"skew_{name}"] = pooled_skew(p, o)["skew"]
        rows.append(row)
    return pd.DataFrame(rows)


def pooled_by(df, col, min_n=50, expost_col="ret_fav"):
    """Pooled ex-ante skewness by `col` + realised ex-post skew side by side.

    Requires a df already passed through add_exante (p_fav_dv, o_fav) and, if
    `expost_col` is present, through returns.add_returns. Returns one row per group.
    """
    from scipy.stats import skew
    rows = []
    for key, g in df.groupby(col, observed=True):
        if len(g) < min_n:
            continue
        d = pooled_skew(g.p_fav_dv.values, g.o_fav.values)
        row = {col: key, "n": len(g), "skew_exante": d["skew"],
               "within_frac": d["within_frac"], "between_frac": d["between_frac"],
               "p_fav_dv_mean": float(g.p_fav_dv.mean()),
               "overround_mean": float(g.overround.mean())}
        if expost_col in g:
            row["skew_expost"] = float(skew(g[expost_col]))
        rows.append(row)
    return pd.DataFrame(rows)
